import { Bungee_Outline, Tajawal } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import RoutesLoading from "@/components/common/routes-loading";
import { ThemeProvider } from "next-themes";
import { SpeedInsights } from "@vercel/speed-insights/next";

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"],
  variable: "--font-tajawal",
  display: "swap",
});

const bungeeOutline = Bungee_Outline({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-aerospace-outline",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ortho AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const currentLanguage = cookieStore.get("current-language")?.value;

  return (
    <html
      lang={currentLanguage === "ar" ? "ar" : "en"}
      dir={currentLanguage === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body
        className={`${tajawal.variable} ${bungeeOutline.variable} antialiased rtl:font-tajawal`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <RoutesLoading />
          <Toaster />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
